name: Deploy to AwardSpace

on:
  push:
    branches:
      - main  # Thay đổi thành nhánh mà bạn muốn theo dõi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compress files
        run: |
          tar -czf myfiles.tar.gz .  # Nén tất cả file trong thư mục hiện tại

      - name: Deploy to AwardSpace
        run: |
          curl -T myfiles.tar.gz --user ${{ secrets.AWARDSPACE_USERNAME }}:${{ secrets.AWARDSPACE_PASSWORD }} myweatherhi.atwebpages.com:/home/www/myweatherhi.atwebpages.com/
