name: Deploy to AwardSpace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AwardSpace
        run: |
          for file in *; do
            curl --ftp-pasv -T "$file" --user ${{ secrets.AWARDSPACE_USERNAME }}:${{ secrets.AWARDSPACE_PASSWORD }} ftp://myweatherhi.atwebpages.com:21/home/www/myweatherhi.atwebpages.com/
          done
